apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "charts.fullname" . }}-configmap
  labels:
  {{- include "charts.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{ .Values.conf | nindent 4 }}
