apiVersion: v1
kind: Secret
metadata:
  name: {{ include "charts.fullname" . }}-secret
  labels:
  {{- include "charts.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    debug: {{ default false .Values.conf.debug }}
    profile_enabled: {{ default false .Values.conf.profile_enabled }}

    kubeconfig: {{ .Values.conf.kubeconfig | default "" | quote }}

    # 'sqlite' or 'mysql'
    db_driver: {{ .Values.conf.db_driver | default "sqlite" | quote }}
    {{- if .Values.conf.db_driver | default "sqlite" | eq "sqlite" }}
    db_database: /data/sqlite.db
    {{ else }}
    db_port: {{ .Values.conf.db_port | default "3306" | quote }}
    db_host: {{ .Values.conf.db_host | default "mysql" | quote }}
    db_database: {{ .Values.conf.db_database | default "mars" | quote }}
    db_username: {{ .Values.conf.db_username | default "mars" | quote }}
    db_password: {{ .Values.conf.db_password | default "" | quote }}
    {{- end }}

    wildcard_domain: {{ .Values.conf.wildcard_domain | default "*.mars.com" | quote }}
    cluster_issuer: {{ .Values.conf.cluster_issuer | default "prod" | quote }}
    external_ip: {{ .Values.conf.external_ip | default "" | quote }}

    gitlab_token: {{ .Values.conf.gitlab_token | default "" |quote }}
    gitlab_baseurl: {{ default "https://gitlab.com/api/v4" .Values.conf.gitlab_baseurl | quote }}

    {{- if not .Values.conf.imagepullsecrets }}
    imagepullsecrets: []
    {{ else if lt (len .Values.conf.imagepullsecrets) 1 }}
    imagepullsecrets: []
    {{ else}}
    imagepullsecrets:
    {{- range .Values.conf.imagepullsecrets }}
      {{- if and (.username | default "" | ne "") (.password | default "" | ne ""  ) }}
      - username: {{ .username | quote }}
        password: {{ .password | quote }}
        {{- if .email }}
        email: {{ .email | quote }}
        {{- end}}
        {{- if .server }}
        server: {{ .server | quote }}
        {{- end}}
      {{- end }}
    {{- end }}
    {{- end }}
