apiVersion: v1
kind: Secret
metadata:
  name: {{ include "charts.fullname" . }}-secret
  labels:
  {{- include "charts.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    debug: {{ default false .Values.conf.debug }}
    profile_enabled: {{ default false .Values.conf.profile_enabled }}
    log_channel: {{ .Values.conf.log_channel }}

    kubeconfig: {{ .Values.conf.kubeconfig | quote }}

    # 'sqlite' or 'mysql'
    db_driver: {{ .Values.conf.db_driver | quote }}
    {{- if .Values.conf.db_driver | eq "sqlite" }}
    db_database: /data/sqlite.db
    {{ else }}
    db_port: {{ .Values.conf.db_port | quote }}
    db_host: {{ .Values.conf.db_host | quote }}
    db_database: {{ .Values.conf.db_database | quote }}
    db_username: {{ .Values.conf.db_username | quote }}
    db_password: {{ .Values.conf.db_password | quote }}
    {{- end }}

    wildcard_domain: {{ .Values.conf.wildcard_domain | quote }}
    cluster_issuer: {{ .Values.conf.cluster_issuer | quote }}
    external_ip: {{ .Values.conf.external_ip | quote }}

    install_timeout: {{ .Values.conf.install_timeout |quote }}

    gitlab_token: {{ .Values.conf.gitlab_token |quote }}
    gitlab_baseurl: {{ .Values.conf.gitlab_baseurl | quote }}

    {{- if not .Values.conf.imagepullsecrets }}
    imagepullsecrets: []
    {{ else if lt (len .Values.conf.imagepullsecrets) 1 }}
    imagepullsecrets: []
    {{ else}}
    imagepullsecrets:
    {{- range .Values.conf.imagepullsecrets }}
      {{- if and (.username | quote | ne "") (.password | quote | ne ""  ) }}
      - username: {{ .username | quote }}
        password: {{ .password | quote }}
        {{- if .email }}
        email: {{ .email | quote }}
        {{- end}}
        {{- if .server }}
        server: {{ .server | quote }}
        {{- end}}
      {{- end }}
    {{- end }}
    {{- end }}
