apiVersion: v1
kind: Secret
metadata:
  name: {{ include "charts.fullname" . }}-secret
  labels:
  {{- include "charts.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    app_port: 6000
    grpc_port: 50000
    log_channel: zap

    upload_dir: /data/uploads
    git_server_cached: true
    kubeconfig: ""
    {{- if eq .Values.mode "standalone" }}
    db_database: /data/dbdata/db.sqlite
      {{- toYaml .Values.standalone_conf | nindent 4 }}
    {{ else }}
      {{- toYaml .Values.cluster_conf | nindent 4 }}
    {{- end }}