apiVersion: v1
kind: Secret
metadata:
  name: {{ include "charts.fullname" . }}-secret
  labels:
  {{- include "charts.labels" . | nindent 4 }}
stringData:
  config.yaml: |-
    {{ .Values.conf | nindent 4 }}
