apiVersion: v1
kind: Secret
metadata:
  name: {{ include "charts.fullname" . }}-secret
  labels:
  {{- include "charts.labels" . | nindent 4 }}
stringData:
  config.yaml: |-
  {{- if eq .Values.mode "standalone" }}
    {{- tpl .Values.standalone_conf . | nindent 4 }}
  {{ else }}
    {{- tpl .Values.cluster_conf . | nindent 4 }}
  {{- end }}