apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts.fullname" . }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 6000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "charts.selectorLabels" . | nindent 4 }}
