{
 "title": "mars-duc",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(go_memstats_alloc_bytes, kubernetes_namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(process_resident_memory_bytes, kubernetes_pod_name)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(process_resident_memory_bytes, app_kubernetes_io_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "总websocket连接数",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mars_websocket_connections{app_kubernetes_io_instance=~\"^($instance)$\", kubernetes_namespace=~\"^($namespace)$\"})"
    }
   ]
  },
  {
   "title": "每个 pod websocket 连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "mars_websocket_connections{app_kubernetes_io_instance=~\"^($instance)$\",kubernetes_namespace=~\"^($namespace)$\",kubernetes_pod_name=~\"^($pod)$\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "实际占用内存 memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app_kubernetes_io_instance=~\"^($instance)$\", kubernetes_namespace=~\"^($namespace)$\",kubernetes_pod_name=~\"^($pod)$\"}",
     "legendFormat": "{{kubernetes_pod_name}} "
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{app_kubernetes_io_instance=~\"^($instance)$\", kubernetes_namespace=~\"^($namespace)$\",kubernetes_pod_name=~\"^($pod)$\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "process memory deriv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{app_kubernetes_io_instance=~\"^($instance)$\", kubernetes_namespace=~\"^($namespace)$\",kubernetes_pod_name=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}} - resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{app_kubernetes_io_instance=~\"^($instance)$\", kubernetes_namespace=~\"^($namespace)$\",kubernetes_pod_name=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}} - virtual"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{app_kubernetes_io_instance=~\"^($instance)$\", kubernetes_namespace=~\"^($namespace)$\",kubernetes_pod_name=~\"^($pod)$\"}",
     "legendFormat": "{{kubernetes_pod_name}}: {{quantile}}"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{app_kubernetes_io_instance=~\"^($instance)$\", kubernetes_namespace=~\"^($namespace)$\",kubernetes_pod_name=~\"^($pod)$\"}",
     "legendFormat": "{{kubernetes_pod_name}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{app_kubernetes_io_instance=~\"^($instance)$\", kubernetes_namespace=~\"^($namespace)$\",kubernetes_pod_name=~\"^($pod)$\"}[30s])",
     "legendFormat": "{{kubernetes_pod_name}} - alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{app_kubernetes_io_instance=~\"^($instance)$\", kubernetes_namespace=~\"^($namespace)$\",kubernetes_pod_name=~\"^($pod)$\"}",
     "legendFormat": "{{kubernetes_pod_name}} - stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{app_kubernetes_io_instance=~\"^($instance)$\", kubernetes_namespace=~\"^($namespace)$\",kubernetes_pod_name=~\"^($pod)$\"}",
     "legendFormat": "{{kubernetes_pod_name}} - heap inuse"
    }
   ]
  },
  {
   "title": "go memstats deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{app_kubernetes_io_instance=~\"^($instance)$\", kubernetes_namespace=~\"^($namespace)$\",kubernetes_pod_name=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{app_kubernetes_io_instance=~\"^($instance)$\", kubernetes_namespace=~\"^($namespace)$\",kubernetes_pod_name=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}} - alloc rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{app_kubernetes_io_instance=~\"^($instance)$\", kubernetes_namespace=~\"^($namespace)$\",kubernetes_pod_name=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}} - stack inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{app_kubernetes_io_instance=~\"^($instance)$\", kubernetes_namespace=~\"^($namespace)$\",kubernetes_pod_name=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}} - heap inuse"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{app_kubernetes_io_instance=~\"^($instance)$\", kubernetes_namespace=~\"^($namespace)$\",kubernetes_pod_name=~\"^($pod)$\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "open fds deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds{app_kubernetes_io_instance=~\"^($instance)$\", kubernetes_namespace=~\"^($namespace)$\",kubernetes_pod_name=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}